services:
  postgres:
    image: postgres:16-alpine
    container_name: dormitory_postgres
    environment:
      POSTGRES_DB: dormitory_db
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dormitory-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dormitory_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dormitory-network
    healthcheck:
      test: [ "CMD", "redis-cli", "png" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  dormitory-network:
    driver: bridge