### Регистрация ROLE_USER
POST http://localhost:8080/api/auth/signUp
Content-Type: application/json

{
  "username": "nikita",
  "fio": "Никита Иванов",
  "password": "secret123",
  "passwordConfirm": "secret123",
  "role": "USER"
}

### Регистрация ROLE_ADMIN
POST http://localhost:8080/api/auth/signUp
Content-Type: application/json

{
  "username": "leha",
  "fio": "Leha Иванова",
  "password": "secret123",
  "passwordConfirm": "secret123",
  "role": "ADMIN"
}

### Регистрация ROLE_INSPECTOR
POST http://localhost:8080/api/auth/signUp
Content-Type: application/json

{
  "username": "pasha",
  "fio": "Pasha Иванова",
  "password": "secret123",
  "passwordConfirm": "secret123",
  "role": "INSPECTOR"
}

### Вход
POST http://localhost:8080/api/auth/signIn
Content-Type: application/json

{
  "username": "leha",
  "password": "secret123"
}
