### Назначить инспектору этажи (ADMIN)
POST http://localhost:8080/api/users/4/floors
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqdWxpYSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MjM5NDkxMywiZXhwIjoxNzcyMzk4NTEzfQ.J9dINnzO4Cl5zp_4X7eMQRDk4Kgo7l6D6ohgrhZtJJc
Content-Type: application/json

{
  "floorNumbers": [3, 4, 5]
}

### Посмотреть этажи инспектора
GET http://localhost:8080/api/users/4/floors
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYXNoYSIsInJvbGUiOiJJTlNQRUNUT1IiLCJpYXQiOjE3NzIzOTQ5NjQsImV4cCI6MTc3MjM5ODU2NH0.uKj-tWfznlARvras9bNvr7abSFH_K9-Ovy5546sz3Y8
