### Назначить инспектору этажи (ADMIN)
POST http://localhost:8080/api/users/1/floors
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIkMmEkMTAkd2hCaDJLQTZTN3U5Q2prR2VTS2RTdUJadVBwU1RkM0pCbnBVRFB1czZ2T1F3Y1B6aC4ueTYiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzI0NDc1MzMsImV4cCI6MTc3MjUzMzkzM30.AaNHkgLXtepWPRsJlCEutm-c3uNrCQ70tQB4eR9zQ_k
Content-Type: application/json

{
  "floorNumbers": [9,13]
}

### Посмотреть этажи инспектора
GET http://localhost:8080/api/users/4/floors
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwYXNoYSIsInJvbGUiOiJJTlNQRUNUT1IiLCJpYXQiOjE3NzIzOTQ5NjQsImV4cCI6MTc3MjM5ODU2NH0.uKj-tWfznlARvras9bNvr7abSFH_K9-Ovy5546sz3Y8
