### Получить всех (нужен токен ADMIN)
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIkMmEkMTAkcnJ6aHBoancwbmRxQ2F6bHpkTEh2ZUs4L1lOejRZRE9wTU5GLzdIQnI5U1ZVWDlkd1FOTUMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzIzNjc1ODksImV4cCI6MTc3MjM3MTE4OX0.cRivAX2OE5ZIJXi4w27oJjY_39Ehd8rhjvI8t4-9gCc

### Получить по id
GET http://localhost:8080/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIkMmEkMTAkcnJ6aHBoancwbmRxQ2F6bHpkTEh2ZUs4L1lOejRZRE9wTU5GLzdIQnI5U1ZVWDlkd1FOTUMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzIzNjc1ODksImV4cCI6MTc3MjM3MTE4OX0.cRivAX2OE5ZIJXi4w27oJjY_39Ehd8rhjvI8t4-9gCc

### Удалить
DELETE http://localhost:8080/api/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIkMmEkMTAkcnJ6aHBoancwbmRxQ2F6bHpkTEh2ZUs4L1lOejRZRE9wTU5GLzdIQnI5U1ZVWDlkd1FOTUMiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NzIzNjc1ODksImV4cCI6MTc3MjM3MTE4OX0.cRivAX2OE5ZIJXi4w27oJjY_39Ehd8rhjvI8t4-9gCc
