spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dormitory_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 200ms

logging:
  level:
    by.bsuir: DEBUG
    org.hibernate.sql: DEBUG
    org.springframework.security: DEBUG