spring:
  application:
    name: dormitory-inspection
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: ${JWT_SECRET:default-dev-secret-ket-change-in-production-minimum-32-characters}
    access-token-expiration: 900000
    refresh-token-expiration: 60480000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true